-- Trigger Call start

CREATE OR REPLACE TRIGGER startCall
    AFTER INSERT
    ON STATE_CHANGE
    FOR EACH ROW
    WHEN ( NEW.CHANGETYPE = 'C' )
DECLARE
    CELL_ID      NUMBER;
    MAX_CALLS    NUMBER;
    ACTIVE_CALLS NUMBER;
    X_0          NUMBER;
    X_1          NUMBER;
    Y_0          NUMBER;
    Y_1          NUMBER;
    EX_ID        NUMBER;

BEGIN
    -- SELECT MAXCALLS + CELL LOCALIZATION FOR CURRENT TELEPHONE
    SELECT CELLID, MAXCALLS, X0, X1, Y0, Y1
    INTO CELL_ID, MAX_CALLS, X_0, X_1, Y_0, Y_1
    FROM CELL
    WHERE X0 <= :NEW.X
      AND :NEW.X <= X1
      AND Y0 <= :NEW.Y
      AND :NEW.Y <= Y1;

    -- SELECT ACTIVE CALLS IN CELL
    SELECT COUNT(*)
    INTO ACTIVE_CALLS
    FROM TELEPHONE
    WHERE PHONESTATE = 'ACTIVE'
      AND X_0 <= :NEW.X
      AND :NEW.X <= X_1
      AND Y_0 <= :NEW.Y
      AND :NEW.Y <= Y_1;

    IF (ACTIVE_CALLS < MAX_CALLS) THEN
        -- SET TELEPHONE ACTIVE
        UPDATE TELEPHONE SET PHONESTATE = 'ACTIVE' WHERE PHONENO = :NEW.PHONENO;
    ELSE
        -- INSERT INTO EXCEPTION_LOG 'M'
        SELECT MAX(EXID) INTO EX_ID FROM EXCEPTION_LOG WHERE CELLID = CELL_ID;
        IF (EX_ID IS NULL) THEN
            EX_ID := 0;
        end if;
        INSERT INTO EXCEPTION_LOG (EXID, CELLID, EXCEPTIONTYPE) VALUES (EX_ID + 1, CELL_ID, 'M');
    end if;
end;