CREATE OR REPLACE TRIGGER es1Trig1
    AFTER UPDATE
    ON DIP
    FOR EACH ROW
    WHEN ( OLD.DNAME = 'ACCOUNTING' AND NEW.DNAME = 'SALES' )
DECLARE

BEGIN
    UPDATE IMP SET SAL = SAL + 100 WHERE DEPTNO = :NEW.DEPTNO;
end;