CREATE OR REPLACE TRIGGER es2Trig
    AFTER INSERT
    ON TICKETS
    FOR EACH ROW
    WHEN ( NEW.CARDNO IS NOT NULL )
DECLARE
    MILESTOADD    NUMBER;
    TOTALMILES    NUMBER;
    OLDSTATUS     VARCHAR(16);
    CORRECTSTATUS VARCHAR(16);
    NOTIFYNUMBER  NUMBER;

BEGIN
    SELECT MILES INTO MILESTOADD FROM FLIGHTS WHERE FLIGHTID = :NEW.FLIGHTID;
    INSERT INTO CREDITS (TICKETID, CARDNO, MILES) VALUES (:NEW.TICKETID, :NEW.CARDNO, MILESTOADD);
    SELECT SUM(MILES) INTO TOTALMILES FROM CREDITS WHERE CARDNO = :NEW.CARDNO;
    SELECT STATUS INTO OLDSTATUS FROM CARDS WHERE CARDNO = :NEW.CARDNO;

    IF (TOTALMILES > 50000) THEN
        CORRECTSTATUS := 'PREMIUM';
    ELSIF (TOTALMILES > 30000) THEN
        CORRECTSTATUS := 'GOLD';
    ELSE
        CORRECTSTATUS := 'GOLD';
    end if;

    IF (OLDSTATUS != CORRECTSTATUS) THEN
        UPDATE CARDS SET STATUS=CORRECTSTATUS WHERE CARDNO = :NEW.CARDNO;

        IF (NOTIFYNUMBER IS NULL) THEN
            INSERT INTO NOTIFY (CARDNO, NOTIFYNO, NOTIFYDATE, OLDSTATUS, NEWSTATUS, TOTALMILES)
            VALUES (:NEW.CARDNO, 0, SYSDATE, OLDSTATUS, CORRECTSTATUS, TOTALMILES);
        ELSE
            INSERT INTO NOTIFY (CARDNO, NOTIFYNO, NOTIFYDATE, OLDSTATUS, NEWSTATUS, TOTALMILES)
            VALUES (:NEW.CARDNO, NOTIFYNUMBER + 1, SYSDATE, OLDSTATUS, CORRECTSTATUS, TOTALMILES);
        end if;

    end if;
end;